### ISSUE TITLE
curl is required to execute

### ISSUE THREAD

**Issue by loekvangool** [kosho/esperf#4]
curl is mentioned as a dependency for developing esperf, but it's also needed for executing:

```
loek@ubuntu:~$ ./esperf
./esperf: error while loading shared libraries: libcurl.so.4: cannot open shared object file: No such file or directory
```

**Comment by loekvangool** [comment]
fixable by `sudo apt-get install libcurl4-openssl-dev` on Debian

**Comment by kosho** [comment]
@loekvangool Thanks for running on Debian! Will soon be mentioned in the README.

**Comment by loekvangool** [comment]
Actually running Ubuntu Server 16.04, but I went with the mother project ;)

**Comment by kosho** [comment]
Now it's mentioned in the README. Thanks for your advice!
